version: '3'

services:
  arkive:
    image: mickeysofine1972/arkive
    build:
      context: .
      dockerfile: ./images/arkive/Dockerfile
    command: gunicorn arkive.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/code/arkive/staticfiles
      - media_volume:/code/arkive/media
    networks:
      - nginx_network
    restart: always

  nginx:
    image: mickeysofine1972/arkive-nginx
    build:
      context: .
      dockerfile: ./images/nginx/Dockerfile
    ports:
      - 80:80
    volumes:
      - static_volume:/code/arkive/staticfiles
      - media_volume:/code/arkive/media
    depends_on:
      - arkive
    networks:
      - nginx_network
    restart: always

  redis:
    image: redis:latest
    hostname: redis
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

networks:
  nginx_network:
    driver: bridge

volumes:
  static_volume:
  media_volume: